### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by neoedmund** [drsjb80/JDNSS#12]
Steven Beaty, your "refactory" break the source compiling. Please fix it ASAP. Thanks.

last commit : 688e3f1f5208ba056ef01d0f24ef53c1f8ce6875
https://travis-ci.org/drsjb80/JDNSS/builds/232086933?utm_source=github_status&utm_medium=notification
```
[ERROR] /home/travis/build/drsjb80/JDNSS/src/main/java/edu/msudenver/cs/jdnss/Query.java:[12,13] cannot find symbol

  symbol:   class Header

  location: class edu.msudenver.cs.jdnss.Query
```

**Comment by drsjb80** [comment]
Header.java is on the dev branch, 2d23359. Note: the dev branch is currently broken and I'm trying to find time to fix it, so I don't recommend it.
