### ISSUE TITLE
Make IPaddress an array

### ISSUE THREAD

**Issue by drsjb80** [drsjb80/JDNSS#27]
So we can listen to multiple ports.

**Comment by drsjb80** [comment]
Actually, I think we want an array of IP/Port.

**Comment by pendula95** [comment]
If I am to bind the server to 0.0.0.0 and have multiple interfaces with multiple IPs. How would you to know from which local IP address to respond to client?

**Comment by drsjb80** [comment]
JDNSS will respond back via the interface the query came in on. The default list of listening ports is 

> "TLS@0.0.0.0@853", "TCP@0.0.0.0@53", "UDP@0.0.0.0@53"

which should cover things. I just tried on a machine using three interfaces and it worked:

> $ nslookup www.test.com 127.0.0.1
> Server:     127.0.0.1
> Address:    127.0.0.1#53
> 
> Name:   www.test.com
> Address: 192.168.1.1
> Name:   www.test.com
> Address: 192.168.1.2
> 
> $ nslookup www.test.com 10.50.36.251
> Server:     10.50.36.251
> Address:    10.50.36.251#53
> 
> Name:   www.test.com
> Address: 192.168.1.1
> Name:   www.test.com
> Address: 192.168.1.2
> 
> $ nslookup www.test.com 147.153.1.2
> Server:     147.153.212.232
> Address:    147.153.212.232#53
> 
> Name:   www.test.com
> Address: 192.168.1.1
> Name:   www.test.com
> Address: 192.168.1.2

If you don't want to monitor all the interfaces, you can use the IPaddresses command-line argument. Let me know if this answers your question. Thanks!

**Comment by drsjb80** [comment]
This has been done.
